apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maps
  namespace: maps
spec:
  interval: 1h
  chart:
    spec:
      chart: podinfo
      version: 6.*
      sourceRef:
        kind: HelmRepository
        name: maps
        namespace: flux-system
  values:
    replicaCount: 0
    ui:
      message: Hello from maps
    resources:
      requests:
        cpu: 5m
        memory: 16Mi
      limits:
        memory: 64Mi
