apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secondary
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/husenkuresh1/gitops-flux
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include mgmt-dev dir
    !/mgmt-dev/**/1-*
