apiVersion: v1
kind: Secret
metadata:
  name: backend-2
  namespace: backend
type: Opaque
stringData:
  password: not-a-real-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-3
  namespace: backend
type: Opaque
stringData:
  password: not-a-real-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-4
  namespace: backend
type: Opaque
stringData:
  password: not-a-real-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-5
  namespace: backend
type: Opaque
stringData:
  password: not-a-real-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-6
  namespace: backend
type: Opaque
stringData:
  password: not-a-real-secret
