apiVersion: v1
kind: ServiceAccount
metadata:
  name: forum
  namespace: forum
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forum
  namespace: forum
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forum
  namespace: forum
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forum
subjects:
- kind: ServiceAccount
  name: default
  namespace: forum
