apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- _namespace.yaml
- flux-system-components.yaml
- lab-secret.yaml
- lab-repo-gitrepository.yaml
- kust-kustomization.yaml
- helmrepository/mailer-helmrepository.yaml
- helmrepository/etl-helmrepository.yaml
