apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loyalty-3
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loyalty-4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loyalty-4
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loyalty-5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loyalty-5
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
