apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: login-3
  namespace: login
spec:
  interval: 1h
  chart:
    spec:
      chart: podinfo
      version: 6.*
      sourceRef:
        kind: HelmRepository
        name: echo
        namespace: flux-system
  values:
    replicaCount: 1
    ui:
      message: Hello from login-3
    resources:
      requests:
        cpu: 5m
        memory: 16Mi
      limits:
        memory: 64Mi
