apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  namespace: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - name: web
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 5m
            memory: 8Mi
          limits:
            memory: 32Mi
