apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reports-2
  namespace: reports
spec:
  interval: 1h
  chart:
    spec:
      chart: podinfo
      version: 6.*
      sourceRef:
        kind: HelmRepository
        name: etl
        namespace: flux-system
  values:
    replicaCount: 1
    ui:
      message: Hello from reports-2
    resources:
      requests:
        cpu: 5m
        memory: 16Mi
      limits:
        memory: 64Mi
