apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: primary
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/husenkuresh1/gitops-flux
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include prod-east dir
    !/prod-east
    # exclude file names starting with '1-'
    /prod-east/**/1-*
